use mysql;

select * from recipe;


-- 만약 RECIPE에 RECIPECAPACITY 열이 없는 경우
ALTER TABLE `RECIPE` ADD `RECIPECAPACITY` INTEGER AFTER `RECIPEREADCOUNT`;
UPDATE RECIPE SET RECIPECAPACITY=1;

-- 만약 RECIPE에 RECIPETHUMBNAIL 열이 없는 경우
ALTER TABLE `RECIPE` ADD `RECIPETHUMBNAIL` VARCHAR(400) AFTER `RECIPEREADCOUNT`;
UPDATE RECIPE SET RECIPETHUMBNAIL=(SELECT PHOTOURL FROM PHOTO WHERE PHOTOTITLE='thumbnail' AND DOCSSEQ=RECIPESEQ);


ALTER TABLE `RECIPE` MODIFY `RECIPETHUMBNAIL` VARCHAR(400);

SELECT * FROM PHOTO;

