package com.recipe.a.dto;

public class RecipeDto {
	private int RECIPESEQ;
	private String RECIPETITLE;
	private String RECIPECONTENT;
	private String RECIPEBIGCATEGORY;
	private String RECIPESMALLCATEGORY;
	private String RECIPEGOODSTAG;
	private int RECIPEPRICE;	// RECIPEPRICE
	
	public RecipeDto() {
	}

	public RecipeDto(int rECIPESEQ, String rECIPETITLE, String rECIPECONTENT, String rECIPEBIGCATEGORY,
			String rECIPESMALLCATEGORY, String rECIPEGOODSTAG, int rECIPEPRICE) {
		super();
		RECIPESEQ = rECIPESEQ;
		RECIPETITLE = rECIPETITLE;
		RECIPECONTENT = rECIPECONTENT;
		RECIPEBIGCATEGORY = rECIPEBIGCATEGORY;
		RECIPESMALLCATEGORY = rECIPESMALLCATEGORY;
		RECIPEGOODSTAG = rECIPEGOODSTAG;
		RECIPEPRICE = rECIPEPRICE;
	}

	public int getRECIPESEQ() {
		return RECIPESEQ;
	}

	public void setRECIPESEQ(int rECIPESEQ) {
		RECIPESEQ = rECIPESEQ;
	}

	public String getRECIPETITLE() {
		return RECIPETITLE;
	}

	public void setRECIPETITLE(String rECIPETITLE) {
		RECIPETITLE = rECIPETITLE;
	}

	public String getRECIPECONTENT() {
		return RECIPECONTENT;
	}

	public void setRECIPECONTENT(String rECIPECONTENT) {
		RECIPECONTENT = rECIPECONTENT;
	}

	public String getRECIPEBIGCATEGORY() {
		return RECIPEBIGCATEGORY;
	}

	public void setRECIPEBIGCATEGORY(String rECIPEBIGCATEGORY) {
		RECIPEBIGCATEGORY = rECIPEBIGCATEGORY;
	}

	public String getRECIPESMALLCATEGORY() {
		return RECIPESMALLCATEGORY;
	}

	public void setRECIPESMALLCATEGORY(String rECIPESMALLCATEGORY) {
		RECIPESMALLCATEGORY = rECIPESMALLCATEGORY;
	}

	public String getRECIPEGOODSTAG() {
		return RECIPEGOODSTAG;
	}

	public void setRECIPEGOODSTAG(String rECIPEGOODSTAG) {
		RECIPEGOODSTAG = rECIPEGOODSTAG;
	}

	public int getRECIPEPRICE() {
		return RECIPEPRICE;
	}

	public void setRECIPEPRICE(int rECIPEPRICE) {
		RECIPEPRICE = rECIPEPRICE;
	}

	@Override
	public String toString() {
		return "RecipeDto [RECIPESEQ=" + RECIPESEQ + ", RECIPETITLE=" + RECIPETITLE + ", RECIPECONTENT=" + RECIPECONTENT
				+ ", RECIPEBIGCATEGORY=" + RECIPEBIGCATEGORY + ", RECIPESMALLCATEGORY=" + RECIPESMALLCATEGORY
				+ ", RECIPEGOODSTAG=" + RECIPEGOODSTAG + ", RECIPEPRICE=" + RECIPEPRICE + "]";
	}
	
	
	
}
