USE MYSQL;

SELECT * FROM RATING;
SELECT * FROM MEMBERS;
SELECT * FROM RECIPE;

UPDATE RECIPE
SET RECIPERATING=(
    SELECT ROUND(AVG(RATINGSCORE), 2)
    FROM RATING
    GROUP BY DOCSSEQ
    )
WHERE RECIPESEQ=2;

SELECT COUNT(*), ROUND(SUM(RATINGSCORE), 2)
FROM RATING
GROUP BY DOCSSEQ;



INSERT INTO RATING(RATINGSEQ, MEMBERID, DOCSSEQ, RATINGCATEGORY, RATINGSCORE, RATINGCOMMENT)
    VALUES(NEXTVAL('RATINGSEQ'), 'test', 2, 'recipe', 3, '맛있어요');
    
INSERT INTO RATING(RATINGSEQ, MEMBERID, DOCSSEQ, RATINGCATEGORY, RATINGSCORE, RATINGCOMMENT)
    VALUES(NEXTVAL('RATINGSEQ'), 'test', 2, 'recipe', 2, '맛없어요');

INSERT INTO RATING(RATINGSEQ, MEMBERID, DOCSSEQ, RATINGCATEGORY, RATINGSCORE, RATINGCOMMENT)
    VALUES(NEXTVAL('RATINGSEQ'), 'test', 2, 'recipe', 3, '보통이에요');
    
INSERT INTO RATING(RATINGSEQ, MEMBERID, DOCSSEQ, RATINGCATEGORY, RATINGSCORE, RATINGCOMMENT)
    VALUES(NEXTVAL('RATINGSEQ'), 'test', 2, 'recipe', 5, '최고에요');

INSERT INTO RATING(RATINGSEQ, MEMBERID, DOCSSEQ, RATINGCATEGORY, RATINGSCORE, RATINGCOMMENT)
    VALUES(NEXTVAL('RATINGSEQ'), 'test', 2, 'recipe', 2, '별로에요');